/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sao;

import config.dbConnector;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import studentviolation.loginForm;
import static studentviolation.registerForm.mail;
import static studentviolation.registerForm.usname;

/**
 *
 * @author NiQby
 */
public class createUsersForm extends javax.swing.JFrame {

    /**
     * Creates new form createUsersForm
     */
    public createUsersForm() {
        initComponents();
    }
     public boolean duplicateCheck(){
    
        dbConnector dbc = new dbConnector();
        
        try{
        String query = "SELECT * FROM tbl_users1  WHERE u_username = '"+ un.getText()+ "' OR u_email = '" + em.getText()+ "'";
            ResultSet resultSet = dbc.getData(query);
            if(resultSet.next()){
                mail = resultSet.getString("u_email");
                if(mail.equals(em.getText())){
                JOptionPane.showMessageDialog(null,"Email Already Exist"); 
                    em.setText("");
                }
                usname = resultSet.getString("u_username");
                if(usname.equals(un.getText())){
                JOptionPane.showMessageDialog(null, "Username is already used");
                    un.setText("");
                }
                System.out.println(""+usname);
                return true;
            }else{
                return false;
            }
        }catch(SQLException ex){
            System.out.println(""+ex);
            return false;
        }
   
    }
      public boolean updateCheck(){
    
        dbConnector dbc = new dbConnector();
        
        try{
        String query = "SELECT * FROM tbl_users1  WHERE( u_username = '"+ un.getText()+ "' OR u_email = '" + em.getText()+ "')AND u_id!='"+uid.getText()+"'";
            ResultSet resultSet = dbc.getData(query);
            if(resultSet.next()){
                mail = resultSet.getString("u_email");
                if(mail.equals(em.getText())){
                JOptionPane.showMessageDialog(null,"Email Already Exist"); 
                    em.setText("");
                }
                usname = resultSet.getString("u_username");
                if(usname.equals(un.getText())){
                JOptionPane.showMessageDialog(null, "Username is already used");
                    un.setText("");
                }
                System.out.println(""+usname);
                return true;
            }else{
                return false;
            }
        }catch(SQLException ex){
            System.out.println(""+ex);
            return false;
        }
   
    }
     
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ln = new javax.swing.JTextField();
        fn = new javax.swing.JTextField();
        em = new javax.swing.JTextField();
        un = new javax.swing.JTextField();
        ps = new javax.swing.JTextField();
        pm = new javax.swing.JComboBox<>();
        pn = new javax.swing.JComboBox<>();
        add = new javax.swing.JButton();
        stats = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        uid = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel2.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/objects.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 180, 490);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 180, 490);

        jPanel3.setBackground(new java.awt.Color(255, 51, 51));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Perpetua", 3, 18)); // NOI18N
        jLabel2.setText("STUDENT VIOLATION MANAGEMENT SYSTEM");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(20, 0, 380, 50);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(180, 0, 420, 50);

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));
        jPanel4.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setText("PROGRAM");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(40, 310, 83, 20);

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel5.setText("USER ID");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(50, 40, 60, 30);

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel6.setText("LAST NAME");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(40, 120, 78, 30);

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel7.setText("EMAIL");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(60, 160, 50, 30);

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel8.setText("USERNAME");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(40, 200, 83, 30);

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel9.setText("PASSWORD");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(40, 240, 83, 30);

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel10.setText("POSITION");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(40, 280, 83, 20);
        jPanel4.add(ln);
        ln.setBounds(130, 120, 180, 30);
        jPanel4.add(fn);
        fn.setBounds(130, 80, 180, 30);
        jPanel4.add(em);
        em.setBounds(130, 160, 180, 30);
        jPanel4.add(un);
        un.setBounds(130, 200, 180, 30);
        jPanel4.add(ps);
        ps.setBounds(130, 240, 180, 30);

        pm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N/A", "BSIT", "BSBA", "BSED", "BEED", "BSHM", "BSTM", "BSCRIM" }));
        jPanel4.add(pm);
        pm.setBounds(130, 310, 180, 20);

        pn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SAO", "DEAN", "" }));
        jPanel4.add(pn);
        pn.setBounds(130, 280, 180, 20);

        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel4.add(add);
        add.setBounds(60, 380, 90, 20);

        stats.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Pending" }));
        stats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statsActionPerformed(evt);
            }
        });
        jPanel4.add(stats);
        stats.setBounds(130, 340, 180, 20);

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel11.setText("USER STATUS");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(20, 340, 100, 20);

        jLabel12.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel12.setText("FIRST NAME");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(40, 80, 83, 30);

        uid.setEnabled(false);
        jPanel4.add(uid);
        uid.setBounds(130, 40, 180, 30);

        update.setText("UPDATE");
        update.setEnabled(false);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel4.add(update);
        update.setBounds(160, 380, 80, 20);

        jButton3.setText("CANCEL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);
        jButton3.setBounds(260, 380, 80, 20);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(180, 50, 420, 440);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed

        if(fn.getText().isEmpty()||ln.getText().isEmpty()||un.getText().isEmpty()||ps.getText().isEmpty()||em.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"All Fields are required!");
        }else if(ps.getText().length()< 8){
            JOptionPane.showMessageDialog(null,"Password should be 8 characters above!");
            ps.setText("");
        } else if(duplicateCheck()){
            System.out.println("Duplicate Exist");

        }else{

            dbConnector dbc = new dbConnector();
            if(  dbc.insertData("INSERT INTO tbl_users1 (u_fname, u_lname, u_email,u_username,u_password,u_position,u_program,u_status)"
                + "VALUES('"+fn.getText()+"','"+ln.getText()+"','"+em.getText()+"',"
                + "'"+un.getText()+"','"+ps.getText()+"','"+pn.getSelectedItem()+"','"+pm.getSelectedItem()+"','"+stats.getSelectedItem()+"')"))
        {
            JOptionPane.showMessageDialog(null,"Inserted Succesfully");
            usersForm ufm = new usersForm();
            ufm.setVisible(true);
            this.dispose();

        }else{
            JOptionPane.showMessageDialog(null,"Connection Error!");
        }
        }
    }//GEN-LAST:event_addActionPerformed

    private void statsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statsActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        usersForm ufm = new usersForm();
        ufm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
      
         if(fn.getText().isEmpty()||ln.getText().isEmpty()||un.getText().isEmpty()||ps.getText().isEmpty()||em.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"All Fields are required!");
        }else if(ps.getText().length()< 8){
            JOptionPane.showMessageDialog(null,"Password should be 8 characters above!");
            ps.setText("");
        } else if(updateCheck()){
            System.out.println("Duplicate Exist");

        }else{
        dbConnector dbc = new dbConnector(); 
        dbc.updateData("UPDATE tbl_users1 SET u_fname ='"+fn.getText()+"', u_lname = '"+ln.getText()+"',u_email = '"+em.getText()+"',u_username ='"+un.getText()+"'"
         + ",u_password ='"+ps.getText()+"',u_position = '"+pn.getSelectedItem()+"',u_program ='"+pm.getSelectedItem()+"',"
         + "u_status = '"+stats.getSelectedItem()+"'WHERE u_id = '"+uid.getText()+"'");
        
        JOptionPane.showMessageDialog(null,"Updated Successfully");
            usersForm ufm = new usersForm();
            ufm.setVisible(true);
            this.dispose();
        
        
    }//GEN-LAST:event_updateActionPerformed

         
         
         
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createUsersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createUsersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createUsersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createUsersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new createUsersForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton add;
    public javax.swing.JTextField em;
    public javax.swing.JTextField fn;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JTextField ln;
    public javax.swing.JComboBox<String> pm;
    public javax.swing.JComboBox<String> pn;
    public javax.swing.JTextField ps;
    public javax.swing.JComboBox<String> stats;
    public javax.swing.JTextField uid;
    public javax.swing.JTextField un;
    public javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
