/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentviolation;

import config.dbConnector;
import java.security.NoSuchAlgorithmException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author NiQby
 */
public class registerForm extends javax.swing.JFrame {

    /**
     * Creates new form registerForm
     */
    public registerForm() {
        initComponents();
    }
    
    
    public static String mail,usname;
    
    public boolean duplicateCheck(){
    
        dbConnector dbc = new dbConnector();
        
        try{
        String query = "SELECT * FROM tbl_user1  WHERE u_username = '"+ un.getText()+ "' OR u_email = '" + em.getText()+ "'";
            ResultSet resultSet = dbc.getData(query);
            if(resultSet.next()){
                mail = resultSet.getString("u_email");
                if(mail.equals(em.getText())){
                JOptionPane.showMessageDialog(null,"Email Already Exist"); 
                    em.setText("");
                }
                usname = resultSet.getString("u_username");
                if(usname.equals(un.getText())){
                JOptionPane.showMessageDialog(null, "Username is already used");
                    un.setText("");
                }
                System.out.println(""+usname);
                return true;
            }else{
                return false;
            }
        }catch(SQLException ex){
            System.out.println(""+ex);
            return false;
        }
   
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ln = new javax.swing.JTextField();
        fn = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        em = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        un = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        ps = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        pm = new javax.swing.JComboBox<>();
        pn = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel2.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/objects.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 180, 490);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 180, 490);

        jPanel3.setBackground(new java.awt.Color(255, 51, 51));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Perpetua", 3, 18)); // NOI18N
        jLabel2.setText("STUDENT VIOLATION MANAGEMENT SYSTEM");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(20, 20, 380, 50);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel3.setText("REGISTRATION FORM");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(120, 70, 180, 18);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(180, 0, 420, 100);

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));
        jPanel4.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setText("PROGRAM");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(40, 260, 83, 20);

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel5.setText("FIRST NAME");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(40, 30, 83, 30);

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel6.setText("LAST NAME");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(40, 70, 78, 30);

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel7.setText("EMAIL");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(60, 110, 50, 30);

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel8.setText("USERNAME");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(40, 150, 83, 30);

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel9.setText("PASSWORD");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(40, 190, 83, 30);

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel10.setText("POSITION");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(40, 230, 83, 20);
        jPanel4.add(ln);
        ln.setBounds(130, 70, 180, 30);
        jPanel4.add(fn);
        fn.setBounds(130, 30, 180, 30);
        jPanel4.add(jTextField3);
        jTextField3.setBounds(130, 70, 180, 30);
        jPanel4.add(em);
        em.setBounds(130, 110, 180, 30);
        jPanel4.add(jTextField5);
        jTextField5.setBounds(130, 110, 180, 30);
        jPanel4.add(un);
        un.setBounds(130, 150, 180, 30);
        jPanel4.add(jTextField7);
        jTextField7.setBounds(130, 150, 180, 30);
        jPanel4.add(ps);
        ps.setBounds(130, 190, 180, 30);
        jPanel4.add(jTextField9);
        jTextField9.setBounds(130, 190, 180, 30);

        pm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N/A", "BSIT", "BSBA", "BSED", "BEED", "BSHM", "BSTM", "BSCRIM" }));
        jPanel4.add(pm);
        pm.setBounds(130, 260, 180, 20);

        pn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SAO", "DEAN", "" }));
        jPanel4.add(pn);
        pn.setBounds(130, 230, 180, 20);

        jButton1.setText("REGISTER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(213, 290, 90, 23);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(180, 100, 420, 390);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
          
        if(fn.getText().isEmpty()||ln.getText().isEmpty()||un.getText().isEmpty()||ps.getText().isEmpty()|| em.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"All Fields are required!");
          }else if(ps.getText().length()< 8){
              JOptionPane.showMessageDialog(null,"Password should be 8 characters above!");
              ps.setText("");
          } else if(duplicateCheck()){
            System.out.println("Duplicate Exist");
          
          }else{
              
       dbConnector dbc = new dbConnector();
       if(  dbc.insertData("INSERT INTO tbl_users1 (u_fname, u_lname, u_email,u_username,u_password,u_position,u_program,u_status)"
               + "VALUES('"+fn.getText()+"','"+ln.getText()+"','"+em.getText()+"',"
                       + "'"+un.getText()+"','"+ps.getText()+"','"+pn.getSelectedItem()+"','"+pm.getSelectedItem()+"','Pending')"))
       {
           JOptionPane.showMessageDialog(null,"Inserted Succesfully");
           loginForm lf = new loginForm();
           lf.setVisible(true);
           this.dispose();
           
      }else{
       JOptionPane.showMessageDialog(null,"Connection Error!");
       }
        }
        
      
       
       
       
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField em;
    private javax.swing.JTextField fn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField ln;
    private javax.swing.JComboBox<String> pm;
    private javax.swing.JComboBox<String> pn;
    private javax.swing.JTextField ps;
    private javax.swing.JTextField un;
    // End of variables declaration//GEN-END:variables
}
